# Importação dos dados

In [8]:
import pandas as pd

df = pd.read_csv('../data/raw/Base Varejo.csv', sep=';', encoding='utf-8')

df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 830000 entries, 0 to 829999
Data columns (total 14 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   DATA         830000 non-null  str
 1   CO_ID        830000 non-null  int64
 2   CL_ID        830000 non-null  int64
 3   CL_GENERO    830000 non-null  str
 4   CL_EC        830000 non-null  int64
 5   CL_FHL       830000 non-null  int64
 6   CL_SEG       830000 non-null  str
 7   PR_ID        830000 non-null  int64
 8   PR_CAT       830000 non-null  str
 9   PR_NOME      830000 non-null  str
 10  Unnamed: 10  0 non-null       float64
 11  Unnamed: 11  0 non-null       float64
 12  Unnamed: 12  0 non-null       float64
 13  Unnamed: 13  0 non-null       float64
dtypes: float64(4), int64(5), str(5)
memory usage: 88.7 MB

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA,NaN,NaN,NaN,NaN
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS,NaN,NaN,NaN,NaN
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO,NaN,NaN,NaN,NaN
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO,NaN,NaN,NaN,NaN

In [9]:
df.describe(include='all')

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
count,830000,830000.00000,830000.000000,830000,830000.000000,830000.00000,830000,830000.000000,830000,830000,0.0,0.0,0.0,0.0
unique,333,NaN,NaN,2,NaN,NaN,3,NaN,7,118,NaN,NaN,NaN,NaN
top,21/08/2020,NaN,NaN,F,NaN,NaN,B,NaN,ALIMENTOS,PRESUNTO COZIDO,NaN,NaN,NaN,NaN
freq,4641,NaN,NaN,432576,NaN,NaN,530163,NaN,434767,14381,NaN,NaN,NaN,NaN
mean,NaN,460045.08989,499.595204,NaN,2.596911,1.14654,NaN,115.051855,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,265465.24754,287.568253,NaN,1.170599,1.41696,NaN,66.129241,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,1000.00000,1.000000,NaN,1.000000,0.00000,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,233117.00000,254.000000,NaN,2.000000,0.00000,NaN,58.000000,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,456517.00000,498.000000,NaN,3.000000,0.00000,NaN,115.000000,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,690132.00000,746.000000,NaN,4.000000,2.00000,NaN,172.000000,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,919822.00000,1000.000000,NaN,5.000000,4.00000,NaN,229.000000,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
print(f"Porcentagem de nulos por coluna:\n\n{df.isnull().sum()*100}")

print(f"\nLinhas duplicadas: {df.duplicated().sum()}")

Porcentagem de nulos por coluna:

DATA                  0
CO_ID                 0
CL_ID                 0
CL_GENERO             0
CL_EC                 0
CL_FHL                0
CL_SEG                0
PR_ID                 0
PR_CAT                0
PR_NOME               0
Unnamed: 10    83000000
Unnamed: 11    83000000
Unnamed: 12    83000000
Unnamed: 13    83000000
dtype: int64

Linhas duplicadas: 96553

# Transformação e limpeza de dados

In [277]:
# Remover colunas com 100% de valores nulos
df.dropna(axis=1, how='all', inplace=True)

In [278]:

# Converter a coluna 'CL_FHL' para o tipo inteiro (int8)
df['CL_FHL'] = df['CL_FHL'].astype('int8')

In [279]:

# Remover linhas duplicadas com base no ID da compra (número da Nota Fiscal)
df.drop_duplicates(subset=['CO_ID'], inplace=True)

In [280]:

# Verificar a distribuição da variável
print(f"Distribuição da variável 'CL_GENERO':\n{df['CL_GENERO'].value_counts(dropna=False)}\n")
print(f"Distribuição da variável 'CL_EC':\n{df['CL_EC'].value_counts(dropna=False)}\n")
print(f"Distribuição da variável 'CL_SEG':\n{df['CL_SEG'].value_counts(dropna=False)}\n")
print(f"Distribuição da variável 'PR_CAT':\n{df['PR_CAT'].value_counts(dropna=False)}\n")

Distribuição da variável 'CL_GENERO':
CL_GENERO
F    9615
M    8856
Name: count, dtype: int64

Distribuição da variável 'CL_EC':
CL_EC
3    4762
4    4551
2    4377
1    4290
5     491
Name: count, dtype: int64

Distribuição da variável 'CL_SEG':
CL_SEG
B    11843
C     5136
A     1492
Name: count, dtype: int64

Distribuição da variável 'PR_CAT':
PR_CAT
ALIMENTOS     9672
HIGIENE       3432
LIMPEZA       3250
BEBIDAS        965
PET            711
ACESSORIOS     327
#N/D           114
Name: count, dtype: int64

In [11]:
import sys, os; sys.path.append(os.path.abspath('..'))
from src.utils import convert_for_category

# Converter as colunas para o tipo categórico
List_column = ['CL_GENERO', 'CL_EC', 'CL_SEG', 'PR_CAT']
convert_for_category(df, List_column)

In [16]:
from src.utils import convert_datetime

convert_datetime(df, 'DATA')

NameError: name 'pd' is not defined

In [ ]:

# Verificar os tipos de dados após as alterações
df.info()

<class 'pandas.DataFrame'>
Index: 18471 entries, 0 to 829933
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   DATA       18471 non-null  datetime64[us]
 1   CO_ID      18471 non-null  int64
 2   CL_ID      18471 non-null  int64
 3   CL_GENERO  18471 non-null  category
 4   CL_EC      18471 non-null  category
 5   CL_FHL     18471 non-null  int8
 6   CL_SEG     18471 non-null  category
 7   PR_ID      18471 non-null  int64
 8   PR_CAT     18471 non-null  category
 9   PR_NOME    18471 non-null  str
dtypes: category(4), datetime64[us](1), int64(3), int8(1), str(1)
memory usage: 956.2 KB