# Importação dos dados

In [1]:
import pandas as pd

df = pd.read_csv('../data/raw/Base Varejo.csv', sep=';', encoding='utf-8')

df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 830000 entries, 0 to 829999
Data columns (total 14 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   DATA         830000 non-null  str
 1   CO_ID        830000 non-null  int64
 2   CL_ID        830000 non-null  int64
 3   CL_GENERO    830000 non-null  str
 4   CL_EC        830000 non-null  int64
 5   CL_FHL       830000 non-null  int64
 6   CL_SEG       830000 non-null  str
 7   PR_ID        830000 non-null  int64
 8   PR_CAT       830000 non-null  str
 9   PR_NOME      830000 non-null  str
 10  Unnamed: 10  0 non-null       float64
 11  Unnamed: 11  0 non-null       float64
 12  Unnamed: 12  0 non-null       float64
 13  Unnamed: 13  0 non-null       float64
dtypes: float64(4), int64(5), str(5)
memory usage: 88.7 MB

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA,NaN,NaN,NaN,NaN
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS,NaN,NaN,NaN,NaN
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO,NaN,NaN,NaN,NaN
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO,NaN,NaN,NaN,NaN

In [2]:
df.describe(include='all')

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
count,830000,830000.00000,830000.000000,830000,830000.000000,830000.00000,830000,830000.000000,830000,830000,0.0,0.0,0.0,0.0
unique,333,NaN,NaN,2,NaN,NaN,3,NaN,7,118,NaN,NaN,NaN,NaN
top,21/08/2020,NaN,NaN,F,NaN,NaN,B,NaN,ALIMENTOS,PRESUNTO COZIDO,NaN,NaN,NaN,NaN
freq,4641,NaN,NaN,432576,NaN,NaN,530163,NaN,434767,14381,NaN,NaN,NaN,NaN
mean,NaN,460045.08989,499.595204,NaN,2.596911,1.14654,NaN,115.051855,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,265465.24754,287.568253,NaN,1.170599,1.41696,NaN,66.129241,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,1000.00000,1.000000,NaN,1.000000,0.00000,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,233117.00000,254.000000,NaN,2.000000,0.00000,NaN,58.000000,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,456517.00000,498.000000,NaN,3.000000,0.00000,NaN,115.000000,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,690132.00000,746.000000,NaN,4.000000,2.00000,NaN,172.000000,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,919822.00000,1000.000000,NaN,5.000000,4.00000,NaN,229.000000,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
print(f"Porcentagem de nulos por coluna:\n\n{df.isnull().sum()*100}")

print(f"\nLinhas duplicadas: {df.duplicated().sum()}")

Porcentagem de nulos por coluna:

DATA                  0
CO_ID                 0
CL_ID                 0
CL_GENERO             0
CL_EC                 0
CL_FHL                0
CL_SEG                0
PR_ID                 0
PR_CAT                0
PR_NOME               0
Unnamed: 10    83000000
Unnamed: 11    83000000
Unnamed: 12    83000000
Unnamed: 13    83000000
dtype: int64

Linhas duplicadas: 96553

# Transformação e limpeza de dados

In [4]:
# Remover colunas com 100% de valores nulos
df.dropna(axis=1, how='all', inplace=True)

In [5]:

# Converter a coluna 'CL_FHL' para o tipo inteiro (int8)
df['CL_FHL'] = df['CL_FHL'].astype('int8')

In [6]:

# Remover linhas duplicadas
df.drop_duplicates(inplace=True)

In [7]:

# Verificar a distribuição da variável
print(f"Distribuição da variável 'CL_GENERO':\n{df['CL_GENERO'].value_counts(dropna=False)}\n")
print(f"Distribuição da variável 'CL_EC':\n{df['CL_EC'].value_counts(dropna=False)}\n")
print(f"Distribuição da variável 'CL_SEG':\n{df['CL_SEG'].value_counts(dropna=False)}\n")
print(f"Distribuição da variável 'PR_CAT':\n{df['PR_CAT'].value_counts(dropna=False)}\n")

Distribuição da variável 'CL_GENERO':
CL_GENERO
F    382427
M    351020
Name: count, dtype: int64

Distribuição da variável 'CL_EC':
CL_EC
3    189048
4    179206
2    172283
1    172010
5     20900
Name: count, dtype: int64

Distribuição da variável 'CL_SEG':
CL_SEG
B    468505
C    205265
A     59677
Name: count, dtype: int64

Distribuição da variável 'PR_CAT':
PR_CAT
ALIMENTOS     384197
HIGIENE       137702
LIMPEZA       128632
BEBIDAS        38264
PET            28553
ACESSORIOS     12871
#N/D            3228
Name: count, dtype: int64

In [ ]:
import sys, os; sys.path.append(os.path.abspath('..'))
from src.utils import change_map
from src.utils import convert_category

# Aplicar a função de mapeamento para a coluna 'CL_EC'
change_map(df, 'CL_EC')

# Converter as colunas para o tipo categórico
List_column = ['CL_GENERO', 'CL_EC', 'CL_SEG', 'PR_CAT']
convert_category(df, List_column)

In [9]:
from src.utils import convert_datetime

# Converter a coluna 'DATA' para o tipo datetime
print(convert_datetime(df, 'DATA'))

Conversão bem-sucedida

In [11]:
#Salva o DataFrame limpo em um novo arquivo CSV
df.to_csv('../data/processed/Base_Varejo_Limpa.csv', index=False, encoding='utf-8')

# Análise dos dados após limpeza

In [ ]:

df.info()
df.head()

<class 'pandas.DataFrame'>
Index: 733447 entries, 0 to 829999
Data columns (total 10 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   DATA       733447 non-null  datetime64[us]
 1   CO_ID      733447 non-null  int64
 2   CL_ID      733447 non-null  int64
 3   CL_GENERO  733447 non-null  category
 4   CL_EC      733447 non-null  category
 5   CL_FHL     733447 non-null  int8
 6   CL_SEG     733447 non-null  category
 7   PR_ID      733447 non-null  int64
 8   PR_CAT     733447 non-null  category
 9   PR_NOME    733447 non-null  str
dtypes: category(4), datetime64[us](1), int64(3), int8(1), str(1)
memory usage: 37.1 MB

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME
0,2019-02-01,1000,534,M,SOLTEIRO,1,C,67,BEBIDAS,REFRIGERANTE GUARANA
1,2019-02-01,1000,534,M,SOLTEIRO,1,C,70,BEBIDAS,REFRIGERANTE OUTROS
2,2019-02-01,1000,534,M,SOLTEIRO,1,C,178,HIGIENE,LENCO UMEDECIDO
3,2019-02-01,1000,534,M,SOLTEIRO,1,C,4,ALIMENTOS,ABACAXI
4,2019-02-01,1000,534,M,SOLTEIRO,1,C,175,LIMPEZA,LIMPADOR MULTIUSO

In [13]:
df.describe(include='all')

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME
count,733447,733447.000000,733447.000000,733447,733447,733447.000000,733447,733447.000000,733447,733447
unique,NaN,NaN,NaN,2,5,NaN,3,NaN,7,118
top,NaN,NaN,NaN,F,SEPARADO,NaN,B,NaN,ALIMENTOS,PRESUNTO COZIDO
freq,NaN,NaN,NaN,382427,189048,NaN,468505,NaN,384197,12719
mean,2020-12-06 11:20:27.215055,459941.034680,499.643996,NaN,NaN,1.146049,NaN,115.037337,NaN,NaN
min,2019-01-04 00:00:00,1000.000000,1.000000,NaN,NaN,0.000000,NaN,1.000000,NaN,NaN
25%,2020-01-09 00:00:00,232895.000000,254.000000,NaN,NaN,0.000000,NaN,58.000000,NaN,NaN
50%,2020-12-27 00:00:00,456422.000000,498.000000,NaN,NaN,0.000000,NaN,115.000000,NaN,NaN
75%,2021-10-20 00:00:00,690100.000000,746.000000,NaN,NaN,2.000000,NaN,172.000000,NaN,NaN
max,2022-12-08 00:00:00,919822.000000,1000.000000,NaN,NaN,4.000000,NaN,229.000000,NaN,NaN
std,NaN,265431.394822,287.561653,NaN,NaN,1.416917,NaN,66.124263,NaN,NaN

In [ ]:
# Porcentagem de vendas por gênero em porcentagem
by_gender = df.groupby("CL_GENERO")["CO_ID"].nunique()
percentage = ((by_gender / by_gender.sum()) * 100).round(2)
print("Vendas por gênero (%):", percentage)

Vendas por gênero (%): CL_GENERO
F    52.05
M    47.95
Name: CO_ID, dtype: float64

In [46]:
# Porcentagem de vendas por categoria
category_percentage = (df["PR_CAT"].value_counts(normalize=True) * 100).round(2)
print("Vendas por categoria (%):", category_percentage)

Vendas por categoria (%): PR_CAT
ALIMENTOS     52.38
HIGIENE       18.77
LIMPEZA       17.54
BEBIDAS        5.22
PET            3.89
ACESSORIOS     1.75
#N/D           0.44
Name: proportion, dtype: float64

In [ ]:
# Porcentagem das categorias por segmento social
all_segments = (df.groupby("CL_SEG")["PR_CAT"].value_counts(normalize=True) * 100).round(2)

for segment in df["CL_SEG"].unique():
    print(
        f"Vendas por categoria na Classe {segment} (%):\n{all_segments.loc[segment]}\n"
    )

Vendas por categoria na Classe C (%):
PR_CAT
ALIMENTOS     52.41
HIGIENE       18.72
LIMPEZA       17.59
BEBIDAS        5.23
PET            3.82
ACESSORIOS     1.78
#N/D           0.44
Name: proportion, dtype: float64

Vendas por categoria na Classe B (%):
PR_CAT
ALIMENTOS     52.40
HIGIENE       18.77
LIMPEZA       17.52
BEBIDAS        5.20
PET            3.93
ACESSORIOS     1.74
#N/D           0.44
Name: proportion, dtype: float64

Vendas por categoria na Classe A (%):
PR_CAT
ALIMENTOS     52.14
HIGIENE       18.98
LIMPEZA       17.53
BEBIDAS        5.31
PET            3.86
ACESSORIOS     1.75
#N/D           0.44
Name: proportion, dtype: float64

In [ ]:
# Mostra a quantidade total de produtos vendidos por ano
for year, quantity in df.groupby(df["DATA"].dt.year).size().items():
    print(f"Ano {year}: Total de produtos vendidos: {quantity} unidades.")

Ano 2019: Total de produtos vendidos: 176103 unidades.
Ano 2020: Total de produtos vendidos: 192804 unidades.
Ano 2021: Total de produtos vendidos: 216813 unidades.
Ano 2022: Total de produtos vendidos: 147727 unidades.

In [81]:
# Mostra os 3 produtod mais vendidos por estado civil


print(f"Produtos mais vendidos por estado civil\n")

for status in df["CL_EC"].unique():

    df_filtrado = df[df["CL_EC"] == status]

    top_3 = df_filtrado["PR_NOME"].value_counts().head(3)

    print(f">{status}")
    for product, quantity in top_3.items():
        print(f"- {product}: {quantity} unidades")
    print("\n")

Produtos mais vendidos por estado civil

>SOLTEIRO
- PRESUNTO COZIDO: 3104 unidades
- DETERGENTE: 1657 unidades
- PAPINHA INFANTIL: 1654 unidades


>CASADO OU UNIÃO ESTÁVEL
- PRESUNTO COZIDO: 2938 unidades
- PRESERVATIVO: 1605 unidades
- CEBOLA: 1589 unidades


>DIVORCIADO
- PRESUNTO COZIDO: 2956 unidades
- CEBOLA: 1579 unidades
- REMOVEDOR: 1568 unidades


>VIÚVO
- PRESUNTO COZIDO: 352 unidades
- LUSTRA MOVEIS: 208 unidades
- MANGA: 208 unidades


>SEPARADO
- PRESUNTO COZIDO: 3369 unidades
- MODELADOR: 1727 unidades
- CHUPETA: 1717 unidades